# Generated by Django 4.2.2 on 2023-06-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "picture",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_column="Title", max_length=32)),
                ("contents", models.CharField(db_column="Contents", max_length=255)),
                ("date", models.DateTimeField()),
                (
                    "pictureid",
                    models.OneToOneField(
                        db_column="PictureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.picture",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("resultnum", models.IntegerField(db_column="resultNum")),
                ("content", models.CharField(db_column="Content", max_length=255)),
                (
                    "petid",
                    models.OneToOneField(
                        db_column="PetID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.pet",
                    ),
                ),
                (
                    "pictureid",
                    models.OneToOneField(
                        db_column="PictureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.picture",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "history",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_column="TItle", max_length=32)),
                ("contents", models.CharField(db_column="Contents", max_length=255)),
                ("date", models.DateTimeField()),
                (
                    "questiontid",
                    models.ForeignKey(
                        db_column="QuestiontID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.question",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
    ]
