# Generated by Django 4.1 on 2023-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='path',
        ),
        migrations.AddField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default=1, upload_to='picture/post/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
