# Generated by Django 4.1 on 2023-06-13 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_picture_path_picture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
