# Generated by Django 4.1 on 2023-06-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_adoptiondate_pet_adoption_date_and_more'),
        ('posts', '0006_remove_answer_date_remove_history_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pictureid',
        ),
        migrations.AddField(
            model_name='question',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='model_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='pet_id',
            field=models.ForeignKey(blank=True, db_column='PetID', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pet'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(default=1, upload_to='picture/post/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='contents',
            field=models.CharField(blank=True, db_column='Contents', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
