# Generated by Django 4.1 on 2023-06-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_questiontid_answer_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(db_column='Questionid', on_delete=django.db.models.deletion.CASCADE, to='posts.question'),
        ),
    ]
