# Generated by Django 4.1 on 2023-06-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospital_id_alter_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='adoptiondate',
            new_name='adoption_date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='neutralization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospitalID',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hos_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='is_neu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '수컷'), ('F', '암컷')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
