# Generated by Django 4.1 on 2023-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pet_adoption_date_alter_pet_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
