# Generated by Django 4.2.2 on 2023-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="hos_profile_img",
            field=models.ImageField(
                default="profile_hos/default.png", upload_to="profile_hos/"
            ),
        ),
    ]
